sudo: required
services:
  - docker

before_install:
  - docker build -t rafayhassan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rafayhassan/docker-react npm run test -- --coverage